version: '2'
services:
  postgres:
    image: 'postgres:latest'
    container_name: postgres
    ports:
      - "5432:5432"
    volumes: 
      - shared_data:/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=sales
    networks:
      - spark_default
volumes: 
  shared_data: